import { Modalidade } from '@/types/modalidade';

export const modalidades: Modalidade[] = [
  {
    id: '1',
    nome: 'Atletismo',
    descricao: 'Velocidade, resistência e técnica nas pistas.',
    categoria: 'Individual',
    maxParticipantes: 200,
    participantesAtuais: 0,
    dataInicio: '2025-11-12',
    dataFim: '2025-11-13',
    local: 'Estádio Central',
    horario: '08:00 - 18:00',
    regras: ['Provas de 100m a 10km', 'Regras da CBAt'],
    premios: ['Medalhas por prova', 'Troféu geral'],
    status: 'inscricoes-abertas',
    modalidadesSexo: [
      'Masculino',
      'Feminino',
      'Master (Masculino 45+, Feminino 40+)',
    ],
    divisoes: ['100m', '200m', '400m', '800m', '1500m', '5000m', '10km'],
  },

  {
    id: '2',
    nome: 'Corrida de Orientação',
    descricao:
      'Desafie-se a encontrar o caminho certo no menor tempo possível.',
    categoria: 'Individual',
    maxParticipantes: 120,
    participantesAtuais: 0,
    dataInicio: '2025-11-13',
    dataFim: '2025-11-13',
    local: 'Parque Ecológico',
    horario: '08:00 - 16:00',
    regras: ['Prova de floresta e sprint', 'Orientação por mapa e bússola'],
    premios: ['Medalhas por categoria', 'Troféu geral'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
    divisoes: [
      'Mulheres até 40 anos',
      'Homens até 40 anos',
      'Mulheres +40 a 59 anos',
      'Homens +40 a 59 anos',
      'Mulheres +60 anos',
      'Homens +60 anos',
    ],
  },

  {
    id: '3',
    nome: 'Triathlon',
    descricao: 'Desafio de resistência com natação, ciclismo e corrida.',
    categoria: 'Individual',
    maxParticipantes: 100,
    participantesAtuais: 0,
    dataInicio: '2025-11-13',
    dataFim: '2025-11-13',
    local: 'Área Externa do Parque',
    horario: '07:00 - 14:00',
    regras: ['Prova contínua com as 3 modalidades', 'Regras da CBTri'],
    premios: ['Medalhas e troféu geral'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
    divisoes: ['Adulto', 'Master (Masculino 45+, Feminino 40+)'],
  },

  {
    id: '4',
    nome: 'Calistenia',
    descricao: 'Força e controle corporal em movimentos livres.',
    categoria: 'Individual',
    maxParticipantes: 80,
    participantesAtuais: 0,
    dataInicio: '2025-11-11',
    dataFim: '2025-11-11',
    local: 'Parque Fitness',
    horario: '09:00 - 16:00',
    regras: ['Avaliação por juízes', 'Categorias de força e resistência'],
    premios: ['Medalhas e troféu'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },

  {
    id: '5',
    nome: 'Natação',
    descricao: 'Provas de velocidade e resistência nas piscinas.',
    categoria: 'Individual e Equipe',
    maxParticipantes: 180,
    participantesAtuais: 0,
    dataInicio: '2025-11-11',
    dataFim: '2025-11-12',
    local: 'Piscina Olímpica',
    horario: '09:00 - 17:00',
    regras: ['Provas de 50m e 400m', 'Provas de revezamento 4x50m'],
    premios: ['Medalhas e troféu por equipe'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino', 'Master'],
    divisoes: [
      {
        tipo: 'Individuais',
        provas: [
          '50m Livre',
          '50m Borboleta',
          '50m Peito',
          '50m Costas',
          '400m Livre',
        ],
      },
      {
        tipo: 'Revezamento',
        provas: ['4x50m Medley', '4x50m Livre'],
      },
      {
        tipo: 'Master',
        categorias: [
          { sexo: 'Masculino', faixaEtaria: '45+' },
          { sexo: 'Feminino', faixaEtaria: '40+' },
        ],
      },
    ],
  },

  {
    id: '6',
    nome: 'Futebol de Campo',
    descricao: 'O esporte mais popular do mundo em sua forma tradicional.',
    categoria: 'Equipe',
    maxParticipantes: 200,
    participantesAtuais: 0,
    dataInicio: '2025-11-08',
    dataFim: '2025-11-12',
    local: 'Campo Principal',
    horario: '08:00 - 18:00',
    regras: ['11 jogadores por time', 'Duração de 2 tempos de 45 minutos'],
    premios: ['Troféu e medalhas'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Master (40+)'],
  },

  {
    id: '7',
    nome: 'Basquetebol',
    descricao: 'Técnica, tática e trabalho em equipe nas quadras.',
    categoria: 'Equipe',
    maxParticipantes: 120,
    participantesAtuais: 0,
    dataInicio: '2025-11-07',
    dataFim: '2025-11-09',
    local: 'Ginásio Poliesportivo',
    horario: '09:00 - 20:00',
    regras: ['Times com 5 jogadores', 'Regras oficiais da FIBA'],
    premios: ['Medalhas e troféu'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },

  {
    id: '8',
    nome: 'Vôlei de Quadra',
    descricao: 'Trabalho em equipe e estratégia em quadra.',
    categoria: 'Equipe',
    maxParticipantes: 100,
    participantesAtuais: 0,
    dataInicio: '2025-11-09',
    dataFim: '2025-11-11',
    local: 'Ginásio Poliesportivo',
    horario: '08:00 - 20:00',
    regras: ['Times com 6 jogadores', 'Melhor de 3 sets'],
    premios: ['Medalhas e troféu'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },

  {
    id: '9',
    nome: 'Futebol de Salão',
    descricao:
      'Habilidade e velocidade em quadra. Disputas emocionantes entre equipes.',
    categoria: 'Equipe',
    maxParticipantes: 120,
    participantesAtuais: 0,
    dataInicio: '2025-11-07',
    dataFim: '2025-11-10',
    local: 'Ginásio Poliesportivo',
    horario: '08:00 - 20:00',
    regras: ['Times com 5 jogadores', 'Duração de 2 tempos de 20 minutos'],
    premios: ['Medalhas e troféu para a equipe campeã'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },

  {
    id: '10',
    nome: 'Vôlei de Praia',
    descricao: 'Competição de duplas na areia com muita emoção.',
    categoria: 'Duplas',
    maxParticipantes: 60,
    participantesAtuais: 0,
    dataInicio: '2025-11-10',
    dataFim: '2025-11-11',
    local: 'Quadra de Areia Central',
    horario: '08:00 - 18:00',
    regras: ['Partidas em duplas', 'Melhor de 3 sets'],
    premios: ['Medalhas e troféu'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },

  {
    id: '11',
    nome: 'Beach Tênis',
    descricao: 'Esporte leve e divertido, disputado em duplas na areia.',
    categoria: 'Duplas',
    maxParticipantes: 60,
    participantesAtuais: 0,
    dataInicio: '2025-11-09',
    dataFim: '2025-11-10',
    local: 'Quadra de Areia Central',
    horario: '08:00 - 18:00',
    regras: ['Partidas em duplas', 'Melhor de 3 sets'],
    premios: ['Medalhas e troféu'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },

  {
    id: '12',
    nome: 'Futevôlei',
    descricao: 'Habilidade e coordenação na areia, em duplas.',
    categoria: 'Duplas',
    maxParticipantes: 60,
    participantesAtuais: 0,
    dataInicio: '2025-11-09',
    dataFim: '2025-11-10',
    local: 'Quadra de Areia Central',
    horario: '08:00 - 18:00',
    regras: ['Partidas em duplas', 'Melhor de 3 sets'],
    premios: ['Medalhas e troféu'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },

  {
    id: '13',
    nome: 'Judô',
    descricao: 'Disciplina, força e técnica no tatame.',
    categoria: 'Individual',
    maxParticipantes: 100,
    participantesAtuais: 0,
    dataInicio: '2025-11-09',
    dataFim: '2025-11-10',
    local: 'Centro Olímpico',
    horario: '08:00 - 18:00',
    regras: ['Sistema eliminatório', 'Regras oficiais da CBJ'],
    premios: ['Medalhas por categoria', 'Troféu por equipe'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
    divisoes: [
      {
        nome: 'Masculino',
        pesos: [
          'Até 66 kg',
          'Até 73 kg',
          'Até 81 kg',
          'Até 90 kg',
          'Até 100 kg',
          '+100 kg',
        ],
      },
      {
        nome: 'Feminino',
        pesos: ['Até 57 kg', 'Até 63 kg', 'Até 70 kg', '+70 kg'],
      },
    ],
  },

  {
    id: '14',
    nome: 'Jiu-Jitsu',
    descricao: 'A arte suave em ação. Competições por peso e faixa.',
    categoria: 'Individual',
    maxParticipantes: 150,
    participantesAtuais: 0,
    dataInicio: '2025-11-05',
    dataFim: '2025-11-06',
    local: 'Academia da PCDF',
    horario: '09:00 - 19:00',
    regras: [
      'Lutas por categoria de peso e faixa',
      'Regras da IBJJF',
      'Kimono obrigatório',
    ],
    premios: ['Medalhas por categoria', 'Troféu para o absoluto'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
    divisoes: [
      {
        nome: 'Faixa Branca',
        pesos: {
          masculino: [
            'Até 62 kg',
            'Até 69 kg',
            'Até 77 kg',
            'Até 85 kg',
            'Até 94 kg',
            '+94 kg',
          ],
          feminino: [
            'Até 49 kg',
            'Até 55 kg',
            'Até 62 kg',
            'Até 70 kg',
            '+70 kg',
          ],
        },
      },
      {
        nome: 'Faixa Azul e Roxa',
        pesos: {
          masculino: [
            'Até 62 kg',
            'Até 69 kg',
            'Até 77 kg',
            'Até 85 kg',
            'Até 94 kg',
            '+94 kg',
          ],
          feminino: [
            'Até 49 kg',
            'Até 55 kg',
            'Até 62 kg',
            'Até 70 kg',
            '+70 kg',
          ],
        },
      },
      {
        nome: 'Faixa Marrom e Preta',
        pesos: {
          masculino: [
            'Até 62 kg',
            'Até 69 kg',
            'Até 77 kg',
            'Até 85 kg',
            'Até 94 kg',
            '+94 kg',
          ],
          feminino: [
            'Até 49 kg',
            'Até 55 kg',
            'Até 62 kg',
            'Até 70 kg',
            '+70 kg',
          ],
        },
      },
    ],
  },

  {
    id: '15',
    nome: 'Tênis de Mesa',
    descricao: 'Velocidade e precisão em disputas individuais.',
    categoria: 'Individual',
    maxParticipantes: 60,
    participantesAtuais: 0,
    dataInicio: '2025-11-07',
    dataFim: '2025-11-08',
    local: 'Ginásio Técnico',
    horario: '09:00 - 17:00',
    regras: ['Melhor de 5 sets', 'Sistema eliminatório'],
    premios: ['Medalhas e troféu'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },

  {
    id: '16',
    nome: 'Xadrez',
    descricao:
      'Estratégia e concentração no tabuleiro. Um desafio para a mente.',
    categoria: 'Individual',
    maxParticipantes: 50,
    participantesAtuais: 0,
    dataInicio: '2025-11-05',
    dataFim: '2025-11-06',
    local: 'Auditório Central',
    horario: '09:00 - 17:00',
    regras: ['Sistema suíço', 'Controle de tempo de 15 minutos'],
    premios: ['Medalhas', 'Troféu para o campeão geral'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },

  {
    id: '17',
    nome: 'Dominó',
    descricao: 'Raciocínio rápido e estratégia em duplas.',
    categoria: 'Duplas',
    maxParticipantes: 40,
    participantesAtuais: 0,
    dataInicio: '2025-11-06',
    dataFim: '2025-11-06',
    local: 'Salão Social',
    horario: '13:00 - 20:00',
    regras: ['Partidas em duplas', 'Melhor de 3 rodadas'],
    premios: ['Medalhas e troféu'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },

  {
    id: '18',
    nome: 'Truco',
    descricao: 'Jogo de cartas tradicional e muito disputado.',
    categoria: 'Duplas',
    maxParticipantes: 40,
    participantesAtuais: 0,
    dataInicio: '2025-11-05',
    dataFim: '2025-11-06',
    local: 'Salão Social',
    horario: '13:00 - 20:00',
    regras: ['Partidas em duplas', 'Melhor de três quedas'],
    premios: ['Medalhas e troféu'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },

  {
    id: '19',
    nome: 'Cabo de Guerra',
    descricao: 'Força, união e estratégia em disputa coletiva.',
    categoria: 'Equipe',
    maxParticipantes: 60,
    participantesAtuais: 0,
    dataInicio: '2025-11-12',
    dataFim: '2025-11-12',
    local: 'Campo Aberto',
    horario: '10:00 - 17:00',
    regras: ['Equipes com 8 integrantes', 'Melhor de 3 puxadas'],
    premios: ['Medalhas e troféu'],
    status: 'inscricoes-abertas',
    modalidadesSexo: ['Masculino', 'Feminino'],
  },
];
