export const modalidades = [
  {
    id: '1',
    nome: 'Futsal',
    descricao: 'O clássico do futebol de salão, com muita habilidade e gols.',
    categoria: 'Coletiva',
    maxParticipantes: 16,
    participantesAtuais: 0,
    dataInicio: '2025-10-20',
    dataFim: '2025-10-26',
    local: 'Ginásio 1',
    horario: '08:00 - 12:00',
    regras: ['Times de 5 jogadores', 'Dois tempos de 20 minutos'],
    premios: ['Troféu e medalhas'],
    status: 'inscricoes-abertas',
  },
  {
    id: '2',
    nome: 'Futebol de Campo',
    descricao:
      'Disputas emocionantes no gramado. Equipes de 11 jogadores em busca da glória.',
    categoria: 'Coletiva',
    maxParticipantes: 16,
    participantesAtuais: 0,
    dataInicio: '2025-10-20',
    dataFim: '2025-10-26',
    local: 'Centro de Treinamento da PMDF',
    horario: '08:00 - 12:00',
    regras: [
      'Times de 11 jogadores',
      'Dois tempos de 45 minutos',
      'Eliminatória simples',
    ],
    premios: ['Troféu para o campeão', 'Medalhas para os 3 primeiros'],
    status: 'inscricoes-abertas',
  },
  {
    id: '3',
    nome: 'Basquetebol',
    descricao:
      'Dribles, arremessos e cestas de três pontos. A elite do basquete em quadra.',
    categoria: 'Coletiva',
    maxParticipantes: 12,
    participantesAtuais: 0,
    dataInicio: '2025-10-22',
    dataFim: '2025-10-26',
    local: 'Ginásio da PCDF',
    horario: '09:00 - 13:00',
    regras: [
      'Equipes de 5 jogadores',
      '4 quartos de 10 minutos',
      'Torneio de dupla eliminação',
    ],
    premios: ['Troféu e medalhas para os campeões'],
    status: 'inscricoes-abertas',
  },
  {
    id: '4',
    nome: 'Vôlei de Quadra',
    descricao:
      'Saques, bloqueios e cortadas. Partidas de vôlei de quadra masculino e feminino.',
    categoria: 'Coletiva',
    maxParticipantes: 24,
    participantesAtuais: 0,
    dataInicio: '2025-10-21',
    dataFim: '2025-10-25',
    local: 'Ginásio do CBMDF',
    horario: '14:00 - 18:00',
    regras: [
      'Equipes de 6 jogadores',
      'Melhor de 3 sets',
      'Fase de grupos e eliminatórias',
    ],
    premios: ['Troféu para equipe campeã', 'Medalhas para os finalistas'],
    status: 'inscricoes-abertas',
  },
  {
    id: '5',
    nome: 'Vôlei de Praia',
    descricao: 'Duplas na areia em busca da vitória sob o sol.',
    categoria: 'Coletiva',
    maxParticipantes: 32,
    participantesAtuais: 0,
    dataInicio: '2025-10-21',
    dataFim: '2025-10-25',
    local: 'Quadras de areia',
    horario: '10:00 - 15:00',
    regras: ['Duplas', 'Melhor de 3 sets'],
    premios: ['Medalhas para os finalistas'],
    status: 'inscricoes-abertas',
  },
  {
    id: '6',
    nome: 'Futevôlei',
    descricao: 'A combinação perfeita de futebol e vôlei na areia.',
    categoria: 'Coletiva',
    maxParticipantes: 32,
    participantesAtuais: 0,
    dataInicio: '2025-10-21',
    dataFim: '2025-10-25',
    local: 'Quadras de areia',
    horario: '10:00 - 15:00',
    regras: ['Duplas', 'Regras adaptadas'],
    premios: ['Medalhas para os finalistas'],
    status: 'inscricoes-abertas',
  },
  {
    id: '7',
    nome: 'Beach Tênis',
    descricao: 'Tênis na praia, com raquetes e muita diversão.',
    categoria: 'Individual',
    maxParticipantes: 32,
    participantesAtuais: 0,
    dataInicio: '2025-10-21',
    dataFim: '2025-10-25',
    local: 'Quadras de areia',
    horario: '10:00 - 15:00',
    regras: ['Partidas individuais ou em duplas', 'Regras adaptadas'],
    premios: ['Medalhas para os finalistas'],
    status: 'inscricoes-abertas',
  },
  {
    id: '8',
    nome: 'Atletismo',
    descricao: 'Provas de corrida, saltos e arremessos. Supere seus limites.',
    categoria: 'Individual',
    maxParticipantes: 100,
    participantesAtuais: 0,
    dataInicio: '2025-11-01',
    dataFim: '2025-11-02',
    local: 'Pista de Atletismo',
    horario: '08:00 - 17:00',
    regras: [
      'Provas de 100m, 200m, salto em distância, etc.',
      'Regras da IAAF',
    ],
    premios: ['Medalhas por prova'],
    status: 'inscricoes-abertas',
  },
  {
    id: '9',
    nome: 'Natação',
    descricao:
      'Velocidade e resistência na piscina. Provas de 50m, 100m e revezamento.',
    categoria: 'Individual',
    maxParticipantes: 100,
    participantesAtuais: 0,
    dataInicio: '2025-11-01',
    dataFim: '2025-11-02',
    local: 'Piscina Olímpica do CBMDF',
    horario: '10:00 - 16:00',
    regras: [
      'Provas de 50m livre, 100m costas, etc.',
      'Classificatórias e finais',
      'Regras da FINA',
    ],
    premios: ['Medalhas de ouro, prata e bronze por prova'],
    status: 'inscricoes-abertas',
  },
  {
    id: '10',
    nome: 'Tênis de Mesa',
    descricao:
      'Agilidade e precisão em alta velocidade. Partidas individuais e em duplas.',
    categoria: 'Individual',
    maxParticipantes: 64,
    participantesAtuais: 0,
    dataInicio: '2025-11-12',
    dataFim: '2025-11-13',
    local: 'Salão de Jogos da PMDF',
    horario: '13:00 - 19:00',
    regras: [
      'Partidas de melhor de 5 sets',
      'Categorias individual e duplas',
      'Eliminatória simples',
    ],
    premios: ['Medalhas para os 3 primeiros de cada categoria'],
    status: 'inscricoes-abertas',
  },
  {
    id: '11',
    nome: 'Triathlon',
    descricao:
      'Natação, ciclismo e corrida. Um desafio completo para os atletas.',
    categoria: 'Resistência',
    maxParticipantes: 50,
    participantesAtuais: 0,
    dataInicio: '2025-11-08',
    dataFim: '2025-11-08',
    local: 'Orla do Lago Paranoá',
    horario: '07:00 - 12:00',
    regras: ['Distâncias Sprint ou Olímpica', 'Regras da CBTri'],
    premios: ['Medalhas e troféus por categoria'],
    status: 'inscricoes-abertas',
  },
  {
    id: '12',
    nome: 'Calistenia',
    descricao:
      'Força, equilíbrio e controle corporal usando o peso do próprio corpo.',
    categoria: 'Individual',
    maxParticipantes: 40,
    participantesAtuais: 0,
    dataInicio: '2025-11-07',
    dataFim: '2025-11-07',
    local: 'Parque de Calistenia',
    horario: '15:00 - 18:00',
    regras: ['Apresentações individuais', 'Juízes avaliarão a performance'],
    premios: ['Medalhas para os melhores'],
    status: 'inscricoes-abertas',
  },
  {
    id: '13',
    nome: 'Jiu Jitsu',
    descricao:
      'A arte suave em ação. Competições por peso e absoluto com os melhores lutadores.',
    categoria: 'Individual',
    maxParticipantes: 150,
    participantesAtuais: 0,
    dataInicio: '2025-11-05',
    dataFim: '2025-11-06',
    local: 'Academia da PCDF',
    horario: '09:00 - 19:00',
    regras: [
      'Lutas por categoria de peso e faixa',
      'Regras da IBJJF',
      'Kimono obrigatório',
    ],
    premios: ['Medalhas por categoria', 'Troféu para o absoluto'],
    status: 'inscricoes-abertas',
  },
  {
    id: '14',
    nome: 'Judô',
    descricao:
      'Caminho suave. Projeções, imobilizações e chaves em busca do ippon.',
    categoria: 'Individual',
    maxParticipantes: 100,
    participantesAtuais: 0,
    dataInicio: '2025-11-03',
    dataFim: '2025-11-04',
    local: 'Dojô da PMDF',
    horario: '09:00 - 18:00',
    regras: ['Lutas por categoria de peso', 'Regras da FIJ'],
    premios: ['Medalhas por categoria'],
    status: 'inscricoes-abertas',
  },
  {
    id: '15',
    nome: 'Cabo de Guerra',
    descricao: 'A prova definitiva de força e trabalho em equipe.',
    categoria: 'Coletiva',
    maxParticipantes: 10,
    participantesAtuais: 0,
    dataInicio: '2025-11-10',
    dataFim: '2025-11-10',
    local: 'Campo de Provas',
    horario: '16:00 - 18:00',
    regras: ['Equipes de 8 pessoas', 'Melhor de 3 puxadas'],
    premios: ['Medalhas para a equipe vencedora'],
    status: 'inscricoes-abertas',
  },
  {
    id: '16',
    nome: 'Truco',
    descricao: 'Blefe, estratégia e sorte neste popular jogo de cartas.',
    categoria: 'Jogos de Salão',
    maxParticipantes: 64,
    participantesAtuais: 0,
    dataInicio: '2025-11-15',
    dataFim: '2025-11-16',
    local: 'Salão de Festas',
    horario: '18:00 - 22:00',
    regras: ['Duplas', 'Regras do truco paulista'],
    premios: ['Troféu para a dupla campeã'],
    status: 'inscricoes-abertas',
  },
  {
    id: '17',
    nome: 'Dominó',
    descricao: 'Raciocínio e parceria para vencer neste clássico jogo de mesa.',
    categoria: 'Jogos de Salão',
    maxParticipantes: 64,
    participantesAtuais: 0,
    dataInicio: '2025-11-15',
    dataFim: '2025-11-16',
    local: 'Salão de Festas',
    horario: '18:00 - 22:00',
    regras: ['Duplas', 'Eliminatória simples'],
    premios: ['Troféu para a dupla campeã'],
    status: 'inscricoes-abertas',
  },
  {
    id: '18',
    nome: 'Xadrez',
    descricao:
      'Estratégia e concentração no tabuleiro. Um desafio para a mente.',
    categoria: 'Individual',
    maxParticipantes: 50,
    participantesAtuais: 0,
    dataInicio: '2025-11-15',
    dataFim: '2025-11-16',
    local: 'Auditório do CBMDF',
    horario: '14:00 - 20:00',
    regras: [
      'Sistema suíço de emparceiramento',
      '5 rodadas',
      'Relógios de xadrez serão utilizados',
    ],
    premios: ['Troféu para o campeão', 'Medalhas para os 3 primeiros'],
    status: 'inscricoes-abertas',
  },
];
