export const pontosFocais = [
  {
    orgao: 'SSPDF',
    nome: 'André Barbosa Sá Teles',
    telefone: '(61) 98316-8043',
    email: null,
  },
  {
    orgao: 'SSPDF',
    nome: 'Isa Paula Corrêa Guimarães',
    telefone: '3441-8815 / 3441-8753',
    email: 'isa.guimaraes@ssp.df.gov.br',
  },
  {
    orgao: 'PMDF',
    nome: 'Cel. Cleber Lacerda',
    telefone: '(61) 99975-2865',
    email: 'cleberlacerda65@gmail.com',
  },
  {
    orgao: 'PMDF',
    nome: 'Cap QOPM Marcelo Languedey Martins',
    telefone: '(61) 99902-4309',
    email: '21100727342@pm.df.gov.br',
  },
  {
    orgao: 'PMDF',
    nome: 'Clark Antônio Rocha de Oliveira',
    telefone: '(61) 98530-5923',
    email: null,
  },
  {
    orgao: 'CBMDF',
    nome: 'Cap QOBM/Comb. André Gonçalves Corrêa da Silva Neto',
    telefone: '(61) 98249-4500',
    email: 'gcp.andre@gmail.com',
  },
  {
    orgao: 'CBMDF',
    nome: 'Sub Ten QBMG-1 Luciano Benevides de Sousa',
    telefone: '(61) 99969-8683',
    email: 'cecaf.sefid@cbm.df.gov.br',
  },
  {
    orgao: 'PCDF',
    nome: 'Humberto Carrilho Santos',
    telefone: '(61) 99217-3162',
    email: null,
  },
  {
    orgao: 'PCDF',
    nome: 'Eduardo Francisco Pereira',
    telefone: '(61) 98586-5186',
    email: 'eduardo.pereira@pcdf.df.gov.br',
  },
  {
    orgao: 'DETRAN/DF',
    nome: 'Erandi da Cruz Silva',
    telefone: '(61) 99927-7067',
    email: null,
  },
  {
    orgao: 'DETRAN/DF',
    nome: 'Glauber Santos Naves Peixoto',
    telefone: '(61) 99102-4222',
    email: 'glauber.peixoto@detran.df.gov.br',
  },
  {
    orgao: 'SEAPE',
    nome: 'Tiago Brandão da Silva',
    telefone: '(61) 98231-6868',
    email: 'tiagobrandao.s@gmail.com',
  },
  {
    orgao: 'SEJUS',
    nome: 'Danilo Henrique Ferreira da Silva',
    telefone: '(61) 98123-4414',
    email: 'danilo.silva@sejus.df.gov.br',
  },
  {
    orgao: 'SEJUS',
    nome: 'Patrícia Carla Rodrigues Barros Esaki',
    telefone: '(61) 98574-3435',
    email: 'patricia.esaki@sejus.df.gov.br',
  },
  {
    orgao: 'PLDF',
    nome: 'Leandro Luiz Fernandes de Lacerda Messere',
    telefone: '(61) 3348-8349 / (61) 99202-7365',
    email: 'leandro.messere@cl.df.gov.br',
  },
  {
    orgao: 'PPF',
    nome: 'Débora Ribeiro Lopes',
    telefone: null,
    email: 'debora.lopes@mj.gov.br',
  },
  {
    orgao: 'PPF',
    nome: 'Brenno Elton Campos Vieira',
    telefone: null,
    email: 'brenno.campos@mj.gov.br',
  },
  {
    orgao: 'PPF',
    nome: 'Jonnathan Alvim Brandão',
    telefone: '(61) 99158-2866',
    email: 'jonnathan.brandao@mj.gov.br',
  },
  {
    orgao: 'PF',
    nome: 'Gláucia Gomes Eustáquio',
    telefone: '(61) 98163-0091',
    email: null,
  },
  {
    orgao: 'PF (DIREF)',
    nome: 'Leontina Adriano de Souza Malheiro',
    telefone: '(61) 98165-5705',
    email: 'leontinaadriano@hotmail.com',
  },
  {
    orgao: 'PF (DIREF)',
    nome: 'Edith Carlos de Lima',
    telefone: '(61) 98221-6566',
    email: 'dithcarlos@hotmail.com',
  },
  {
    orgao: 'PRF',
    nome: 'Eduardo Lôbo de Araújo',
    telefone: '(61) 98336-8315',
    email: 'eduardo.lobo@prf.gov.br',
  },
  {
    orgao: 'PLSF',
    nome: 'Lívia Soares Vieira',
    telefone: '(61) 98628-0347',
    email: 'liviavi@senado.leg.br',
  },
  {
    orgao: 'PLSF',
    nome: 'Isabella Tostes de Araújo',
    telefone: '(32) 99915-4080',
    email: 'isabella.araujo@senado.leg.br',
  },
  {
    orgao: 'PLCD',
    nome: 'Joyce',
    telefone: '(61) 98597-1785',
    email: null,
  },
  {
    orgao: 'PLCD',
    nome: 'Antônio Fortunato Júnior',
    telefone: '(61) 98400-9362',
    email: null,
  },
];
