import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Provider from '@/lib/Provider';
import { Tooltip } from '@/components/ui/tooltip';
import { Toaster } from '@/components/ui/sonner';
import Navbar from '@/components/ui/NavBar';
import { Analytics } from '@vercel/analytics/next';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Olinsesp VIII',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='pt-BR'>
      <body className={`${inter.className}`}>
        <Provider>
          <Tooltip>
            <Toaster />
            <div className='min-h-screen'>
              <Navbar />
              {children}
              <Analytics />
            </div>
          </Tooltip>
        </Provider>
      </body>
    </html>
  );
}
