import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Provider from '@/lib/Provider';
import { Tooltip } from '@/components/ui/tooltip';
import { Toaster } from '@/components/ui/sonner';
import Navbar from '@/components/ui/NavBar';
import { Analytics } from '@vercel/analytics/next';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'VIII Olinsesp',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='pt-BR'>
      <body className={`${montserrat.className}`}>
        <Provider>
          <Tooltip>
            <Toaster />
            <div className='min-h-screen relative'>
              <div className="absolute inset-0 bg-[url('/bgimage.jpeg')] bg-repeat opacity-35 pointer-events-none"></div>
              <div className='relative'>
                <Navbar />
                {children}
                <Analytics />
              </div>
            </div>
          </Tooltip>
        </Provider>
      </body>
    </html>
  );
}
