export const classificacoes = [
  {
    id: '1',
    modalidadeId: '2',
    categoria: 'Adulto',
    posicao: 1,
    lotacao: 'PMDF',
    pontuacao: 95,
    observacoes: 'Campeão da modalidade',
  },
  {
    id: '2',
    modalidadeId: '2',
    categoria: 'Adulto',
    posicao: 2,
    lotacao: 'CBMDF',
    pontuacao: 88,
    observacoes: 'Vice-campeão da modalidade',
  },
  {
    id: '3',
    modalidadeId: '2',
    categoria: 'Adulto',
    posicao: 3,
    lotacao: 'PCDF',
    pontuacao: 82,
    observacoes: 'Terceiro lugar na modalidade',
  },
  {
    id: '4',
    modalidadeId: '7',
    categoria: 'Adulto',
    posicao: 1,
    lotacao: 'PMDF',
    pontuacao: 92,
    observacoes: 'Campeão da modalidade',
  },
  {
    id: '5',
    modalidadeId: '7',
    categoria: 'Adulto',
    posicao: 2,
    lotacao: 'CBMDF',
    pontuacao: 87,
    observacoes: 'Vice-campeão da modalidade',
  },
  {
    id: '6',
    modalidadeId: '14',
    categoria: 'Adulto',
    posicao: 1,
    lotacao: 'PMDF',
    pontuacao: 94,
    observacoes: 'Campeão da modalidade',
  },
  {
    id: '7',
    modalidadeId: '14',
    categoria: 'Adulto',
    posicao: 2,
    lotacao: 'PCDF',
    pontuacao: 89,
    observacoes: 'Vice-campeão da modalidade',
  },
  {
    id: '8',
    modalidadeId: '13',
    categoria: '100m',
    posicao: 1,
    inscricaoId: '5',
    pontuacao: 96,
    tempo: '10.45s',
    distancia: '100m',
    observacoes: 'Recorde do evento',
  },
  {
    id: '10',
    modalidadeId: '6',
    categoria: '50m Livre',
    posicao: 1,
    inscricaoId: '3',
    pontuacao: 93,
    tempo: '25.32s',
    distancia: '50m',
    observacoes: 'Estilo perfeito',
  },
];
